#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ttfunk
Version  : 1.4.0
Release  : 5
URL      : https://rubygems.org/downloads/ttfunk-1.4.0.gem
Source0  : https://rubygems.org/downloads/ttfunk-1.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 Ruby
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec

%description
TTFunk is a TrueType font parser written in pure ruby.
= Installation
The recommended installation method is via Rubygems.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ttfunk-1.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-ttfunk.gemspec

%build
gem build rubygem-ttfunk.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ttfunk-1.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ttfunk-1.4.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/CHANGELOG
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/GPLv2
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/GPLv3
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/data/fonts/DejaVuSans.ttf
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/examples/metrics.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/directory.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/encoding/mac_roman.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/encoding/windows_1252.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/reader.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/resource_file.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/subset.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/subset/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/subset/mac_roman.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/subset/unicode.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/subset/unicode_8bit.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/subset/windows_1252.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/subset_collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/cmap.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/cmap/format00.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/cmap/format04.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/cmap/format06.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/cmap/format10.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/cmap/format12.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/cmap/subtable.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/glyf.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/glyf/compound.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/glyf/simple.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/head.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/hhea.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/hmtx.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/kern.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/kern/format0.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/loca.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/maxp.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/name.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/os2.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/post.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/post/format10.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/post/format20.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/post/format30.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/post/format40.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/sbix.rb
/usr/lib64/ruby/gems/2.3.0/gems/ttfunk-1.4.0/lib/ttfunk/table/simple.rb
/usr/lib64/ruby/gems/2.3.0/specifications/ttfunk-1.4.0.gemspec
